In [1]:
import numpy as np

In [2]:
a = [10, 20, 30, 40, 50]

In [3]:
a

[10, 20, 30, 40, 50]

In [4]:
type(a)

list

In [5]:
b = np.array(a)

In [6]:
b

array([10, 20, 30, 40, 50])

In [7]:
print(b)

[10 20 30 40 50]


In [8]:
b.shape

(5,)

In [9]:
c = np.array([5, 4, 3, 2, 1])

In [10]:
c

array([5, 4, 3, 2, 1])

In [11]:
b + c

array([15, 24, 33, 42, 51])

In [12]:
b + 5

array([15, 25, 35, 45, 55])

In [13]:
a + 5

TypeError: ignored

In [14]:
a + [5, 4, 3, 2, 1]

[10, 20, 30, 40, 50, 5, 4, 3, 2, 1]

In [15]:
np.sum(b)

150

In [16]:
np.mean(b)

30.0

In [17]:
np.max(b)

50

In [18]:
np.min(b)

10

In [19]:
c = b / 3

In [20]:
c

array([ 3.33333333,  6.66666667, 10.        , 13.33333333, 16.66666667])

In [21]:
np.round(c, 1)

array([ 3.3,  6.7, 10. , 13.3, 16.7])

In [22]:
np.round(c, 3)

array([ 3.333,  6.667, 10.   , 13.333, 16.667])

In [23]:
np.round(c, 0)

array([ 3.,  7., 10., 13., 17.])

In [24]:
b[0]

10

In [25]:
b[-1]

50

In [26]:
b[1:3]

array([20, 30])

In [27]:
b[2:]

array([30, 40, 50])

In [28]:
np.sum(b[2:])

120

In [29]:
b[1] = 200

In [30]:
b

array([ 10, 200,  30,  40,  50])

In [31]:
d = np.arange(5)

In [32]:
d

array([0, 1, 2, 3, 4])

In [33]:
e = np.arange(3, 8)

In [34]:
e

array([3, 4, 5, 6, 7])

In [35]:
f = np.arange(3, 8, 2)

In [36]:
f

array([3, 5, 7])

In [37]:
g = np.zeros(5)

In [38]:
g

array([0., 0., 0., 0., 0.])

In [39]:
h = np.ones(5)

In [40]:
h

array([1., 1., 1., 1., 1.])

In [41]:
b

array([ 10, 200,  30,  40,  50])

In [43]:
bb = b

In [44]:
bb

array([ 10, 200,  30,  40,  50])

In [45]:
bb[0] = 100

In [46]:
bb

array([100, 200,  30,  40,  50])

In [47]:
b

array([100, 200,  30,  40,  50])

In [48]:
b == bb

array([ True,  True,  True,  True,  True])

In [49]:
b is bb

True

In [50]:
bb = b.copy()

In [51]:
bb

array([100, 200,  30,  40,  50])

In [52]:
b[2] = 300

In [53]:
b

array([100, 200, 300,  40,  50])

In [54]:
bb

array([100, 200,  30,  40,  50])

In [55]:
b is bb

False