In [1]:
import numpy as np

In [2]:
a = np.arange(5, 45, 5).reshape(2, 4)

In [3]:
b = np.arange(20, 36, 2).reshape(2, 4)

In [4]:
a

array([[ 5, 10, 15, 20],
       [25, 30, 35, 40]])

In [5]:
b

array([[20, 22, 24, 26],
       [28, 30, 32, 34]])

In [6]:
a + b

array([[25, 32, 39, 46],
       [53, 60, 67, 74]])

In [7]:
a - b

array([[-15, -12,  -9,  -6],
       [ -3,   0,   3,   6]])

In [8]:
a * b

array([[ 100,  220,  360,  520],
       [ 700,  900, 1120, 1360]])

In [9]:
a / b

array([[0.25      , 0.45454545, 0.625     , 0.76923077],
       [0.89285714, 1.        , 1.09375   , 1.17647059]])

In [10]:
a // b

array([[0, 0, 0, 0],
       [0, 1, 1, 1]])

In [11]:
a % b

array([[ 5, 10, 15, 20],
       [25,  0,  3,  6]])

In [12]:
a * 10

array([[ 50, 100, 150, 200],
       [250, 300, 350, 400]])

In [13]:
a

array([[ 5, 10, 15, 20],
       [25, 30, 35, 40]])

In [14]:
c = a * 10

In [15]:
c

array([[ 50, 100, 150, 200],
       [250, 300, 350, 400]])

In [16]:
b

array([[20, 22, 24, 26],
       [28, 30, 32, 34]])

In [17]:
bb = b.reshape(4, 2)

In [18]:
bb

array([[20, 22],
       [24, 26],
       [28, 30],
       [32, 34]])

In [20]:
# 행렬곱 (내적)
a @ bb

array([[1400, 1500],
       [3480, 3740]])

In [21]:
a = np.arange(1, 15)

In [22]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [23]:
a > 10

array([False, False, False, False, False, False, False, False, False,
       False,  True,  True,  True,  True])

In [24]:
a == 5

array([False, False, False, False,  True, False, False, False, False,
       False, False, False, False, False])

In [25]:
a[a > 5]

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14])

In [26]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [27]:
a[a < 5] = 5

In [28]:
a

array([ 5,  5,  5,  5,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [29]:
a[a > 10] = 10

In [30]:
a

array([ 5,  5,  5,  5,  5,  6,  7,  8,  9, 10, 10, 10, 10, 10])