In [1]:
import pandas as pd

In [2]:
a = {'a': 10, 'b': 20, 'c': 30, 'd': 40, 'e': 50}

In [3]:
a

{'a': 10, 'b': 20, 'c': 30, 'd': 40, 'e': 50}

In [4]:
type(a)

dict

In [5]:
b = pd.Series(a)

In [6]:
b

a    10
b    20
c    30
d    40
e    50
dtype: int64

In [7]:
type(b)

pandas.core.series.Series

In [8]:
b.shape

(5,)

In [11]:
import numpy as np

In [12]:
aa = np.arange(3, 10)

In [13]:
aa

array([3, 4, 5, 6, 7, 8, 9])

In [14]:
bb = pd.Series(aa)

In [15]:
bb

0    3
1    4
2    5
3    6
4    7
5    8
6    9
dtype: int64

In [16]:
type(bb)

pandas.core.series.Series

In [17]:
bb.shape

(7,)

In [18]:
a

{'a': 10, 'b': 20, 'c': 30, 'd': 40, 'e': 50}

In [19]:
a.keys()

dict_keys(['a', 'b', 'c', 'd', 'e'])

In [20]:
a.values()

dict_values([10, 20, 30, 40, 50])

In [21]:
b

a    10
b    20
c    30
d    40
e    50
dtype: int64

In [22]:
b.index

Index(['a', 'b', 'c', 'd', 'e'], dtype='object')

In [23]:
b.values

array([10, 20, 30, 40, 50])

In [24]:
c = [10, 20, 30, 40, 50]

In [25]:
d = pd.Series(c)

In [26]:
d

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [27]:
type(d)

pandas.core.series.Series

In [28]:
d.shape

(5,)

In [29]:
d.index

RangeIndex(start=0, stop=5, step=1)

In [30]:
d.values

array([10, 20, 30, 40, 50])

In [31]:
e = ['a', 'b', 'c', 'd', 'e']

In [32]:
f = [10, 20, 30, 40, 50]

In [33]:
g = pd.Series(f, index = e)

In [34]:
g

a    10
b    20
c    30
d    40
e    50
dtype: int64

In [35]:
g['a']

10

In [36]:
g[0]

10

In [37]:
g['a':'d']

a    10
b    20
c    30
d    40
dtype: int64